# Generated by Django 5.0.4 on 2024-05-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField()),
                ('q2', models.CharField(max_length=50)),
                ('q3', models.CharField(max_length=50)),
                ('q4', models.CharField(max_length=50)),
                ('q5', models.CharField(max_length=50)),
                ('q6', models.CharField(max_length=50)),
                ('q7', models.CharField(max_length=50)),
                ('q8', models.CharField(max_length=50)),
                ('q9', models.CharField(max_length=50)),
                ('q10', models.CharField(max_length=50)),
                ('q11', models.CharField(max_length=50)),
                ('q12', models.CharField(max_length=50)),
                ('q13', models.CharField(max_length=50)),
                ('q14', models.CharField(max_length=50)),
            ],
        ),
    ]
